# Generated by Django 5.2.17 on 2026-09-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Daily Payment Summary',
                'verbose_name_plural': 'Daily Payment Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
    ]
